OUTPUT_BASE_DIR: ('/Midgard/home/pshi/run_logs/unet/')
DATASETS:
  TRAIN: ("/local_storage/datasets/xview2/full_new/train/",)
  VALIDATION: ("/local_storage/datasets/xview2/full_new/test/",)
  TEST: ("/local_storage/datasets/xview2/full_new/real_test_set/",)
  DEBUG_TRAIN: ("/storage/yonk/debug_new/train/",)
  DEBUG_VALIDATION: ("/storage/yonk/debug_new/test/",)
  DEBUG_TEST: ("/storage/yonk/debug_new/test/",)
OPTUNA:
  DB_PATH: 'sqlite:////Midgard/home/pshi/run_logs/optuna.db'