OUTPUT_BASE_DIR: ('/home/david/trains/run_logs/unet/')
DATASETS:
  TRAIN: ("/storage2/yonk/full_new/train/",)
  TEST: ("/storage2/yonk/full_new/test/",)
  INFERENCE: ("/storage2/yonk/full_new/real_test_set/",)
  DEBUG_TRAIN: ("/storage2/yonk/full_new/train/",)
  DEBUG_TEST: ("/storage2/yonk/full_new/test/",)
  DEBUG_INFERENCE: ("/storage2/yonk/full_new/real_test_set/",)