SEED: 1339 # best seed so far 1339 or 43
MODEL:
  OUT_CHANNELS: 5
  IN_CHANNELS: 4
  LOSS_TYPE: 'SoftDiceMulticlassLoss'
  TOPOLOGY: [64, 128, 256, 512,]
  BLOCK_TYPE: 'Double' # Double = Double conv, Triple = Triple conv, for greater receptive field
  SIMPLE_INTERPOLATION: False # True: Bilinear interpo, False: Deconv interpo
  MULTISCALE_CONTEXT: # For U-Net bottleneck context module
    ENABLED: False
    TYPE: 'Simple' # [Simple, PyramidSum, ParallelSum]
    DILATION: []
  USE_ATTENTION: False
  PRETRAINED:
    ENABLED: False
    NAME: '' # Name of the pretrained model
    CP_FILE: '' # Checkpoint file
    ENCODER_ONLY: False # full, encoder
    INCLUDE_INPUT_LAYER: False # If true, weights from input layer will be included too (only if they have the same dims
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
  SIAMESE:
    ENABLED: False
    TYPE: 'DPN92' # DPN92 is default, or SENET152
    PRETRAINED: False
  COMPLEX_ARCHITECTURE:
    ENABLED: False
    TYPE: 'pspnet'
  BACKGROUND:   # Include background class in the inference
    TYPE: 'new-class' # 'new-class', 'no-damage', 'None'
    MASK_OUTPUT: False
    MASKED_GRADIENT: False

THRESH: 0.1 # Best threshold (only to be filled after running final model evaluation)
DATASETS:
  TRAIN: ("/local_storage/datasets/xview2/full_new/train/",)
  TEST: ("/local_storage/datasets/xview2/full_new/test/",)
  INFERENCE: ("/local_storage/datasets/xview2/full_new/real_test_set/",)
  PRE_OR_POST: 'post' # 'pre' vs 'post' disaster images to use
  LOCALIZATION_MASK:
    ENABLED: False
    TRAIN_USE_GTS_MASK: False # If false, we will use predicted localization to train
  INCLUDE_PRE_DISASTER: False # If true, a Pre Disaster will be stacked
  USE_CLAHE_VARI: False
OUTPUT_BASE_DIR: ('/Midgard/home/pshi/run_logs/dmg/')
TRAINER:
  LR: 0.0001
  BATCH_SIZE: 0
  EPOCHS: 1000
  INFERENCE_BATCH_SIZE: 3
  CE_CLASS_BALANCE:
    ENABLED: False
    WEIGHTS: [0.036552, 0.0040245, 0.003355, 0.003686, 0.95238]

DATALOADER:
  NUM_WORKER: 0
  SHUFFLE: True

AUGMENTATION:
  # Random cropping of the images
  RESIZE: False # target image size (before cropping)
  RESIZE_RATIO: 1.0
  CROP_TYPE: 'none'
  CROP_SIZE: 1024
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  ENABLE_VARI: False # False NDVI for detecting vegetation
  RANDOM_FLIP_ROTATE: False





