_BASE_: "dmg_siamese_combostack_os_per_class_ce_balance_pretrained.yaml"
DEBUG: True
DATALOADER:
  NUM_WORKER: 0
  SHUFFLE: False
TRAINER:
  EPOCHS: 1
#DATASETS:
#  LABEL_FORMAT: 'ordinal'
MODEL:
  OUT_CHANNELS: 4
AUGMENTATION:
  CROP_TYPE: 'importance'
  CROP_SIZE: 512
  IMAGE_OVERSAMPLING_TYPE: 'per_class'