_BASE_: "abl_siam_resnet_pretrain_hcombo_cos_perclass_imp_loc.yaml"
DEBUG: True
DATALOADER:
  NUM_WORKER: 0
  SHUFFLE: False
TRAINER:
  EPOCHS: 1
#DATASETS:
#  LABEL_FORMAT: 'ordinal'
MODEL:
  OUT_CHANNELS: 4
AUGMENTATION:
  CROP_TYPE: 'importance'
  CROP_SIZE: 512
  IMAGE_OVERSAMPLING_TYPE: 'per_class'