_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'ComboLoss'
  IN_CHANNELS: 6
  SIAMESE:
    ENABLED: True
    PRETRAINED: True
    TYPE: SENET152
DATASETS:
  LOCALIZATION_MASK:
    ENABLED: False
    TRAIN_USE_GTS_MASK: False # If false, we will use predicted localization to train
  INCLUDE_PRE_DISASTER: True
TRAINER:
  BATCH_SIZE: 2
  CE_CLASS_BALANCE:
    ENABLED: True
    WEIGHTS: [0.036552, 0.0040245, 0.003355, 0.003686, 0.95238]
DATALOADER:
  NUM_WORKER: 8
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 512
  IMAGE_OVERSAMPLING_TYPE: 'simple'




