_BASE_: "dmg_arch.yaml"
MODEL:
  IN_CHANNELS: 6
  BLOCK_TYPE: 'Triple'
  SIAMESE:
    ENABLED: True
    PRETRAINED: True
    TYPE: 'DPN92'
DATASETS:
  LOCALIZATION_MASK:
    ENABLED: False
    TRAIN_USE_GTS_MASK: False # If false, we will use predicted localization to train
  INCLUDE_PRE_DISASTER: True
TRAINER:
  BATCH_SIZE: 6




