_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'ComboLoss'
  IN_CHANNELS: 6
DATASETS:
  TEST: ("/Midgard/Data/pshi/datasets/xview2/xview2_validation/test/",)
  INCLUDE_PRE_DISASTER: True
TRAINER:
  BATCH_SIZE: 12
DATALOADER:
  NUM_WORKER: 8
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 512
  IMAGE_OVERSAMPLING_TYPE: 'simple'




