_BASE_: "s1s2_allbands.yaml"
THRESH: 0.38
DATALOADER:
  LABEL: 'cadastre'
DATASETS:
  TRAIN: ("/storage/shafner/urban_extraction/urban_extraction_sthlm/train/",)
  TEST: ("/storage/shafner/urban_extraction/urban_extraction_sthlm/test/",)
  INFERENCE: ("/storage/yonk/debug_new/test/",)
  USE_CLAHE_VARI: False
OUTPUT_BASE_DIR: ('/storage/shafner/run_logs/unet/')
TRAINER:
  LR: 0.0001
  BATCH_SIZE: 16
  EPOCHS: 100