_BASE_: "s1s2_allbands.yaml"
THRESH: 0.00
DATASETS:
  TRAIN: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_bing/train/",)
  TEST: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_bing/test/",)
DATALOADER:
  LABEL: 'bing'
TRAINER:
  EPOCHS: 50