_BASE_: "s1s2_allbands.yaml"
THRESH: 0.00
DATASETS:
  TRAIN: ("/storage/shafner/urban_extraction/urban_extraction_bing/train/",)
  TEST: ("/storage/shafner/urban_extraction/urban_extraction_bing/test/",)
DATALOADER:
  LABEL: 'bing'
OUTPUT_BASE_DIR: ('/storage/shafner/run_logs/unet/')