_BASE_: "base.yaml"
DEBUG: True
MODEL:
  LOSS_TYPE: 'FrankensteinEdgeLoss'
  OUT_CHANNELS: 1
  IN_CHANNELS: 3
  POOLING_TYPE: '2Stride'
  LAST_LAYER_RESIDUAL: True
  TOPOLOGY: [128, 128, 256, 512,]
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  USE_CLAHE_VARI: False
TRAINER:
  LR: 0.001
  BATCH_SIZE: 8
  EDGE_LOSS_SCALE: 2
DATALOADER:
  NUM_WORKER: 0
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
  RANDOM_FLIP_ROTATE: True
