_BASE_: "frankenstein_oversample_3conv.yaml"
THRESH: 0.88
MODEL:
  LOSS_TYPE: 'FrankensteinEdgeLoss'
  OUT_CHANNELS: 1
  BLOCK_TYPE: 'Triple'
  EDGE_WEIGHTED_LOSS:
    TYPE: 'edge_loss_weight_mask_32' # Which preprocessed edge weight to use: e.g. edge_loss_weight_mask_32
    SCALE: 200
    WARMUP_ENABLED: True
    WARMUP_START: 20000
    WARMUP_END: 30000


