_BASE_: "frankenstein_oversample_3conv.yaml"
THRESH: 0.52
MODEL:
  LOSS_TYPE: 'FrankensteinEdgeLoss'
  OUT_CHANNELS: 1
  BLOCK_TYPE: 'Triple'
TRAINER:
  EDGE_LOSS_SCALE: 1
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'

