_BASE_: "unet_combo2x.yaml"
SEED: 1339
MODEL:
  IN_CHANNELS: 4

AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
  ENABLE_VARI: True
