_BASE_: "unet_dice.yaml"
THRESH: 1
MODEL:
  LOSS_TYPE: 'ComboLoss'
  OUT_CHANNELS: 1
  BLOCK_TYPE: 'Triple'
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'

