_BASE_: "frankenstein_oversample_3conv.yaml"
THRESH: 0.52
MODEL:
  EDGE_WEIGHTED_LOSS:
    TYPE: 'edge_loss_weight_mask_32' # Which preprocessed edge weight to use: e.g. edge_loss_weight_mask_32
    SCALE: 200
  USE_ATTENTION: True
TRAINER:
  BATCH_SIZE: 14


