_BASE_: "base.yaml"
THRESH: 0.52
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  BLOCK_TYPE: 'Triple'
DATASETS:
  TEST: ("/local_storage/datasets/xview2/full_new/test/",)
TRAINER:
  BATCH_SIZE: 16
DATALOADER:
  NUM_WORKER: 16
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'

